version: '3.9'
services:
  db:
    image: postgres:14-alpine
    env_file:
      - .env
    ports:
      - 5432:5432
    volumes:
      - db_data:/var/lib/postgresql/data

  redis:
    image: redis:7-alpine
    env_file:
      - .env
    volumes:
      - redis_data:/data

  app:
    build: .
    env_file:
      - .env
    command: bundle exec rails s -p 3000 -b '0.0.0.0'
    ports:
      - 3000:3000
    depends_on:
      - db
      - redis
    tty: true
    stdin_open: true
    volumes:
      - .:/app
      - bundler_gems:/usr/local/bundle/
      - node_modules:/app/node_modules

volumes:
  db_data:
  redis_data:
  bundler_gems:
  node_modules: