version: '3.9'
services:
  database:
    image: postgres:15.2-alpine
    env_file:
      - .env
    ports:
      - 5432:5432
    volumes:
      - database_data:/var/lib/postgresql/data

  redis:
    image: redis:7-alpine
    env_file:
      - .env
    volumes:
      - redis_data:/data

  app:
    build: .
    env_file:
      - .env
    command: bundle exec rails s -p 3000 -b '0.0.0.0'
    ports:
      - 3000:3000
    depends_on:
      - database
      - redis
    tty: true
    stdin_open: true
    volumes:
      - .:/app
      - bundler_gems:/usr/local/bundle/

volumes:
  database_data:
  redis_data:
  bundler_gems:
